MantenimientoProductoCSharp/Controllers/LoginController.cs
using MantenimientoProductoCSharp.Models;
using ProductoDao.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MantenimientoProductoCSharp.Controllers
{
    public class LoginController : Controller
    {
        //
        // GET: /Index/

        public ActionResult Ingreso()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(UsuarioModel usuarioModel)
        {
            if (ModelState.IsValid) {
                UsuarioBusiness business = new UsuarioBusiness();
                Usuario usuario = new Usuario();
                usuario.clave = usuarioModel.clave;
                usuario.nombre = usuarioModel.nombre;
                if (business.Buscar(usuario) != null)
                {
                    
                    return RedirectToAction("Menu","Menu");
                }
            }
            ModelState.AddModelError("UsuarioError", "Datos incorrectos");
            return View("Ingreso");                
        }
    }
}

MantenimientoProductoCSharp/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MantenimientoProductoCSharp.Controllers
{
    public class MenuController : Controller
    {
        //
        // GET: /Menu/

        public ActionResult Menu()
        {
            return View();
        }

    }
}

MantenimientoProductoCSharp/Views/Shared/NavbarLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/bootstrap/css")
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Mantenimiento Producto", "Menu", "Menu",null, new { @class = "navbar-brand" })
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i><i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><i class="fa fa-sign-out fa-fw"></i>@Html.ActionLink("Logout","Ingreso","Login")
                    </li>
                </ul>
            </li>
        </ul>
    </nav>

    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MantenimientoProductoCSharp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/bootstrap/css")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>