MantenimientoProductoCSharp/Controllers/CategoriaController.cs
using MantenimientoProductoCSharp.Models;
using MantenimientoProductoCSharp.ViewModel.Categoria;
using ProductoDao.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MantenimientoProductoCSharp.Controllers
{
    public class CategoriaController : Controller
    {
        //
        // GET: /Producto/

        public ActionResult Listar()
        {
            CategoriaListarViewModel viewModel = new CategoriaListarViewModel();
            CategoriaBusiness business = new CategoriaBusiness();
            viewModel.listaCategoria = business.Listar().ConvertAll(x => new CategoriaModel
            {
                idCategoria = x.idCategoria,
                descripcion = x.descripcion,
                nombre = x.nombre
            });

            ModelState.Merge((ModelStateDictionary)TempData["ModelState"]);
            @ViewBag.status = TempData["Status"];

            return View(viewModel);
        }

        public ActionResult Detalle(int? id)
        {
            CategoriaBusiness business = new CategoriaBusiness();
            if (id.HasValue)
            {
                CategoriaModel model = (CategoriaModel)business.Obtener(id.Value);
                return View(model);
            }
            return RedirectToAction("Listar");
        }

        public ActionResult Editar(int? id)
        {
            CategoriaBusiness business = new CategoriaBusiness();
            var viewModel = new CategoriaListarViewModel();

            viewModel.listaCategoria = business.Listar().ConvertAll(x => new CategoriaModel
            {
                idCategoria = x.idCategoria,
                descripcion = x.descripcion,
                nombre = x.nombre
            });

            if (id.HasValue)
            {
                CategoriaModel categoria = (CategoriaModel)business.Obtener(id.Value);
                viewModel.categoria = categoria;
            }

            @ViewBag.status = TempData["Status"];

            return View("Listar", viewModel);
        }
        public ActionResult Eliminar(int? id)
        {
            CategoriaBusiness business = new CategoriaBusiness();
            Categoria categoria = new Categoria();
            categoria.idCategoria = id.GetValueOrDefault();
            try
            {
                business.Eliminar(categoria);
                TempData["Status"] = "Se eliminó la categoría satisfactoriamente.";
            }
            catch (Exception ex)
            {
                TempData["Status"] = "Ocurrió un error. Puede que esta categoría este siendo usada por un producto";
            }

            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult InsertarEditar(CategoriaListarViewModel viewModel)
        {
            CategoriaBusiness business = new CategoriaBusiness();
            Categoria categoria = new Categoria();
            categoria = (Categoria)viewModel.categoria;
            Categoria busqueda = business.Buscar(categoria);

            //Busqueda de repetidos en categoria
            if (busqueda != null)
            {
                TempData["Status"] = "La categoría " + categoria.nombre + " ya existe.";
                return RedirectToAction("Editar");
            }

            if (ModelState.IsValid)
            {
                if (categoria.idCategoria == 0)
                {
                    viewModel.categoria = (CategoriaModel)business.Insertar(categoria);
                    TempData["Status"] = "La categoría ha sido insertada correctamente.";

                }
                else
                {
                    business.Actualizar(categoria);
                    TempData["Status"] = "La categoría se modificó satisfactoriamente.";
                }

                return RedirectToAction("Editar", new { id = viewModel.categoria.idCategoria });
            }

            TempData["ModelState"] = ModelState;
            return RedirectToAction("Listar");
        }
    }
}

MantenimientoProductoCSharp/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MantenimientoProductoCSharp.Controllers
{
    public class MenuController : Controller
    {
        //
        // GET: /Menu/

        public ActionResult Menu()
        {
            return View();
        }

    }
}

MantenimientoProductoCSharp/Views/Categoria/Detalle.cshtml
@model MantenimientoProductoCSharp.Models.CategoriaModel

@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/NavbarLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1 id="txtTitulo">Detalle de categoría</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            @Html.ActionLink("Regresar","Listar")
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.idCategoria)
                                @Html.TextBoxFor(model => model.idCategoria, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.nombre)
                                @Html.TextBoxFor(model => model.nombre, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.descripcion)
                                @Html.TextBoxFor(model => model.descripcion, new { @class = "form-control" })
                            </div>
                            @Html.ActionLink("Regresar","Listar")
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MantenimientoProductoCSharp/Views/Categoria/Listar.cshtml
@model MantenimientoProductoCSharp.ViewModel.Categoria.CategoriaListarViewModel

@{
    ViewBag.Title = "Producto";
    Layout = "~/Views/Shared/NavbarLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="page-header" id="txtTitulo">Ingresar o editar categorías</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            @Html.ActionLink("Regresar", "Menu", "Menu")
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-warning" id="txtMensaje">
                @Html.ValidationSummary()
                @ViewBag.status
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-4">
                            @using (Html.BeginForm("InsertarEditar", "Categoria", FormMethod.Post))
                            {
                                <div class="form-group">
                                    @Html.LabelFor(model => model.categoria.idCategoria)
                                    @Html.TextBoxFor(model => model.categoria.idCategoria, new { @class = "form-control", @readonly = "readonly" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.categoria.nombre)
                                    @Html.TextBoxFor(model => model.categoria.nombre, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.categoria.nombre)
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.categoria.descripcion)
                                    @Html.TextBoxFor(model => model.categoria.descripcion, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.categoria.descripcion)
                                </div>
                                <input type="submit" class="btn btn-primary" value="Aceptar" name="btnAceptar" id="btnAceptar" />
                            }
                        </div>
                        <div class="col-lg-8">
                            <table id="tabla" class="table table-striped table-bordered table-hover" border="1">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Nombre</th>
                                        <th>Descripción</th>
                                        <th>Detalle</th>
                                        <th>Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.listaCategoria)
                                        {
                                        <tr>
                                            <td>@Html.DisplayFor(modelItem => item.idCategoria)</td>
                                            <td>@Html.DisplayFor(modelItem => item.nombre)</td>
                                            <td>@Html.DisplayFor(modelItem => item.descripcion)</td>

                                            <td>@Html.ActionLink("Detalle", "Detalle", "Categoria", new { id = item.idCategoria }, new { @id = "btnDetalle" + item.idCategoria })</td>
                                            <td>@Html.ActionLink("Editar", "Editar", "Categoria", new { id = item.idCategoria }, new { @id = "btnEditar" + item.idCategoria })
                                            @Html.ActionLink("Eliminar", "Eliminar", "Categoria", new { id = item.idCategoria }, new { @id = "btnEliminar" + item.idCategoria })
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>