MantenimientoProductoCSharp/Controllers/ProductoController.cs
using MantenimientoProductoCSharp.Models;
using MantenimientoProductoCSharp.ViewModel.Producto;
using ProductoDao.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MantenimientoProductoCSharp.Controllers
{
    public class ProductoController : Controller
    {
        //
        // GET: /Producto/

        public ActionResult Listar()
        {
            var viewModel = new ProductoListarViewModel();
            ProductoBusiness business = new ProductoBusiness();
            CategoriaBusiness businessCategoria = new CategoriaBusiness();
            viewModel.listaProducto = business.Listar().ConvertAll(x => new ProductoModel
            {
                idProducto = x.idProducto,
                stock = x.stock,
                idCategoria = x.idCategoria,
                fechaVencimiento = x.fechaVencimiento,
                categoria = x.Categoria,
                nombre = x.nombre
            });

            viewModel.listaCategoria = businessCategoria.Listar().ConvertAll(x => new SelectListItem 
            {
                Text = x.nombre,
                Value = x.idCategoria.ToString()
            });

            //Magia que permite pasar errores de un controller a otro
            ModelState.Merge((ModelStateDictionary)TempData["ModelState"]);

            ViewBag.status = TempData["Status"];

            return View(viewModel);
        }

        public ActionResult Detalle(int? id)
        {
            ProductoBusiness business = new ProductoBusiness();
            if (id.HasValue)
            {
                ProductoModel model = (ProductoModel)business.Obtener(id.Value);
                return View(model);
            }
            return RedirectToAction("Listar");
        }

        public ActionResult Editar(int? id)
        {
            ProductoBusiness business = new ProductoBusiness();
            CategoriaBusiness businessCategoria = new CategoriaBusiness();
            var viewModel = new ProductoListarViewModel();

            viewModel.listaProducto = business.Listar().ConvertAll(x => new ProductoModel
            {
                idProducto = x.idProducto,
                stock = x.stock,
                idCategoria = x.idCategoria,
                fechaVencimiento = x.fechaVencimiento,
                categoria = x.Categoria,
                nombre = x.nombre
            });

            viewModel.listaCategoria = businessCategoria.Listar().ConvertAll(x => new SelectListItem
            {
                Text = x.nombre,
                Value = x.idCategoria.ToString()
            });

            ProductoModel producto = (ProductoModel)business.Obtener(id.Value);
            viewModel.producto = producto;

            @ViewBag.status = TempData["Status"];

            return View("Listar", viewModel);
        }
        public ActionResult Eliminar(int? id)
        {
            ProductoBusiness business = new ProductoBusiness();
            Producto producto = new Producto();
            producto.idProducto = id.GetValueOrDefault();
            try
            {
                business.Eliminar(producto);
                TempData["Status"] = "Se eliminó el producto satisfactoriamente.";
            }
            catch (Exception ex)
            {

                TempData["Status"] = "Ocurrió un error. ¿Existe el producto a eliminar?";
            }

            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult InsertarEditar(ProductoListarViewModel viewModel)
        {
            ProductoBusiness business = new ProductoBusiness();
            CategoriaBusiness businessCategoria = new CategoriaBusiness();
            Producto producto = new Producto();
            producto = (Producto)viewModel.producto;

            if (businessCategoria.Obtener(producto.idCategoria) == null)
            {
                ModelState.AddModelError("ForeignKey","La categoría debe estar registrada en el sistema.");
            }

            if (ModelState.IsValid)
            {
                if (producto.idProducto == 0)
                {
                    viewModel.producto = (ProductoModel)business.Insertar(producto);
                    TempData["Status"] = "El producto ha sido insertado correctamente.";

                }
                else
                {
                    business.Actualizar(producto);
                    TempData["Status"] = "El producto se modificó correctamente.";
                }

                return RedirectToAction("Editar", new { id = viewModel.producto.idProducto });
            }

            TempData["ModelState"] = ModelState;
            return RedirectToAction("Listar");
        }
    }
}

MantenimientoProductoCSharp/Views/Producto/Detalle.cshtml
@model MantenimientoProductoCSharp.Models.ProductoModel

@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/NavbarLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1 id="txtTitulo">Detalle de producto</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            @Html.ActionLink("Regresar", "Listar")
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                @Html.LabelFor(x => x.idProducto)
                                @Html.TextBoxFor(x => x.idProducto, new { @class = "form-control", @readonly = "readonly" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(x => x.nombre)
                                @Html.TextBoxFor(x => x.nombre, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(x => x.stock)
                                @Html.TextBoxFor(x => x.stock, new { @class = "form-control", @readonly = "readonly" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(x => x.categoria.idCategoria)
                                @Html.TextBoxFor(x => x.categoria.idCategoria, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(x => x.fechaVencimiento)
                                @Html.TextBoxFor(x => x.fechaVencimiento, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1>Categoría asociada</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            @Html.ActionLink("Regresar", "Listar")
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                @Html.LabelFor(x => x.categoria.idCategoria)
                                @Html.TextBoxFor(x => x.categoria.idCategoria, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(x => x.categoria.nombre)
                                @Html.TextBoxFor(x => x.categoria.nombre, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                            @Html.LabelFor(x => x.categoria.descripcion)
                            @Html.TextBoxFor(x => x.categoria.descripcion, new { @class = "form-control", @readonly = "readonly" })
                            <div class="form-group">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MantenimientoProductoCSharp/Views/Producto/Listar.cshtml
@model MantenimientoProductoCSharp.ViewModel.Producto.ProductoListarViewModel

@{
    ViewBag.Title = "Listar";
    Layout = "~/Views/Shared/NavbarLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 id="txtTitulo">Ingresar o editar productos</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
             @Html.ActionLink("Regresar","Listar")
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-warning" id="txtMensaje">
                @Html.ValidationSummary()
                @ViewBag.status
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-4">
                            @using (Html.BeginForm("InsertarEditar", "Producto", FormMethod.Post))
                            {
                                <div class="form-group">
                                    @Html.LabelFor(x => x.producto.idProducto)
                                    @Html.TextBoxFor(x => x.producto.idProducto, new { @class = "form-control", @readonly = "readonly" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(x => x.producto.nombre)
                                    @Html.TextBoxFor(x => x.producto.nombre, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.producto.nombre)
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(x => x.producto.stock)
                                    @Html.TextBoxFor(x => x.producto.stock, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.producto.stock)
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(x => x.producto.idCategoria)
                                    @Html.DropDownListFor(x => x.producto.idCategoria, Model.listaCategoria, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.producto.idCategoria)
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(x => x.producto.fechaVencimiento)
                                    @Html.TextBoxFor(x => x.producto.fechaVencimiento,"{0:dd/MM/yyyy}", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.producto.fechaVencimiento)

                                </div>
                                <input class="btn btn-primary" type="submit" value="Aceptar" name="btnAceptar" id="btnAceptar" />
                            }
                        </div>
                        <div class="col-lg-8">
                            <table id="tabla" class="table table-striped table-bordered table-hover" border="1">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Nombre</th>
                                        <th>Stock</th>
                                        <th>Categoria</th>
                                        <th>Fecha</th>
                                        <th>Detalle</th>
                                        <th>Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.listaCategoria != null)
                                    {
                                        foreach (var item in Model.listaProducto)
                                        {
                                        <tr>
                                            <td>@Html.DisplayFor(x => item.idProducto)</td>
                                            <td>@Html.DisplayFor(x => item.nombre)</td>
                                            <td>@Html.DisplayFor(x => item.stock)</td>
                                            <td>@Html.DisplayFor(x => item.categoria.nombre)</td>
                                            <td>@Html.DisplayFor(x => item.fechaVencimiento)</td>
                                            <td>@Html.ActionLink("Detalle", "Detalle", "Producto", new { id = item.idProducto }, new { @id = "btnDetalle" + item.idProducto })</td>
                                            <td>@Html.ActionLink("Editar", "Editar", "Producto", new { id = item.idProducto }, new { @id = "btnEditar" + item.idProducto })
                                                @Html.ActionLink("Eliminar", "Eliminar", "Producto", new { id = item.idProducto }, new { @id = "btnEliminar" + item.idProducto })</td>
                                        </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>